import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import type { ReactNode } from "react";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Layout } from "antd";
import { StoreProvider } from "@/store/StoreProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface ICandidats{
  id: number;
  email: string;
  first_name: string;
  last_name: string;
  avatar: string;
}

export default async function RootLayout({ children }: { children: ReactNode }) {
  const res= await fetch('https://reqres.in/api/users');
    const response = await res.json();
    console.log(response)

  return (
    <StoreProvider>
    <html lang="fr">
      <body>
      <AntdRegistry>{children}</AntdRegistry>

      {response.data.map((d: ICandidats)=>{
      return <p key={d.id}>{d.first_name}</p>
      })}
      </body>
    </html>
    </StoreProvider>
  );
}
